// CA Revalidation Data - Converted from CSV
const caRevalidationData = [
  {
    id: 21,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-060",
    sterileFilterTag: "B10L1-FSL33",
    roomName: "BOTTLE CLEANING-P",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 22,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-065",
    sterileFilterTag: "B10L1-FSL34",
    roomName: "BOTTLE FILLING-P (LOW RH) (BOTTLE FILLING LINE)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 24,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-067",
    sterileFilterTag: "B10L1-FSL37",
    roomName: "BLISTER PACKING-P (LOW RH) (BLISTER PACKING MACHINE)",
    using: true,
    sampling: false,
    samplingDate: "29/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 23,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-068",
    sterileFilterTag: "B10L1-FSL36",
    roomName: "STRIP PACKING-P (LOW RH) (DRUM TIPPER) & (STRIP PACKING MACHINE)",
    using: false,
    sampling: false,
    samplingDate: "29/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 11,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-091",
    sterileFilterTag: "B10L1-FSL-19",
    roomName: "BOTTLE CLEANING (BOTTLE CLEANING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 10,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-092",
    sterileFilterTag: "B10L1-FSL-18",
    roomName: "POS FILLING (LOW RH) (BOTTLE FILLING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 1,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-093",
    sterileFilterTag: "B10L1-FSL-02",
    roomName: "BLISTER PACKING 1 (BLISTER PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 2,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-094",
    sterileFilterTag: "B10L1-FSL-03",
    roomName: "BLISTER PACKING 2 (DRUM TIPPER)  (BLISTER PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 3,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-094",
    sterileFilterTag: "B10L1-FSL-04",
    roomName: "BLISTER PACKING 2 (BLISTER PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 4,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-095",
    sterileFilterTag: "B10L1-FSL-06",
    roomName: "BLISTER PACKING 3 (BLISTER PACKING MACHINE)",
    using: true,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 5,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-096",
    sterileFilterTag: "B10L1-FSL-07",
    roomName: "BLISTER PACKING 4 (BLISTER PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 6,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-097",
    sterileFilterTag: "B10L1-FSL-10",
    roomName: "BLISTER PACKING 5 (BLISTER PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 7,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-098",
    sterileFilterTag: "B10L1-FSL-12",
    roomName: "BLISTER PACKING 6 (BLISTER PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 8,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-099",
    sterileFilterTag: "B10L1-FSL-14",
    roomName: "BLISTER PACKING 4 (LOW RH) (BLISTER PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 9,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-100",
    sterileFilterTag: "B10L1-FSL-16",
    roomName: "BLISTER PACKING 5 (LOW RH) (BLISTER PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 14,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-101",
    sterileFilterTag: "B10L1-FSL-22",
    roomName: "BOTTLE FILLING (LOW RH) (BOTTLE FILLING MACHINE)",
    using: true,
    sampling: false,
    samplingDate: "29/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 12,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-107",
    sterileFilterTag: "B10L1-FSL-20",
    roomName: "STRIP PACKING 1 (LOW RH) (DRUM TIPPER) & (STRIP PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "28/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 13,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-108",
    sterileFilterTag: "B10L1-FSL-21",
    roomName: "SACHET PACKING (LOW RH) (STRIP PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "29/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 20,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-109",
    sterileFilterTag: "B10L1-FSL-31",
    roomName: "STRIP PACKING 2 (DRUM TIPPER) & (STRIP PACKING MACHINE)",
    using: true,
    sampling: true,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 19,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-110",
    sterileFilterTag: "B10L1-FSL-30",
    roomName: "STRIP PACKING 3 (DRUM TIPPER) & (STRIP PACKING MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "29/8/2025",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 18,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-117",
    sterileFilterTag: "B10L1-FSL-29",
    roomName: "USED EQUIPMENT",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 17,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-121",
    sterileFilterTag: "B10L1-FSL-27",
    roomName: "TABLETS INSPECTION 1 (LOW RH) (TABLET INSPECTION MACHINE)",
    using: false,
    sampling: true,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 15,
    building: "B.10",
    floor: "FL.1",
    roomNo: "10-1-126",
    sterileFilterTag: "B10L1-FSL-23",
    roomName: "BOTTLE CLEANING (BOTTLE CLEANING MACHINE)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  // Floor 3 data
  {
    id: 25,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-050",
    sterileFilterTag: "B10L3-FSL39",
    roomName: "TABLETS INSPECTION 1  (TABLET INSPECTION MACHINE) & (DRUM TIPPER)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 26,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-052",
    sterileFilterTag: "B10L3-FSL40",
    roomName: "TABLETS INSPECTION 2  (TABLET INSPECTION MACHINE) & (DRUM TIPPER)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 27,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-058",
    sterileFilterTag: "B10L3-FSL29",
    roomName: "COATING 1",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 28,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-059",
    sterileFilterTag: "B10L3-FSL24",
    roomName: "COATING SOLUTION PREPARATION 1  (SOLUTION PREPARATION TANK)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 29,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-060",
    sterileFilterTag: "B10L3-FSL25",
    roomName: "COATING SOLUTION PREPARATION 2  (SOLUTION PREPARATION TANK)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 30,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-061",
    sterileFilterTag: "B10L3-FSL23",
    roomName: "COATING 2",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 31,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-062",
    sterileFilterTag: "B10L3-FSL21",
    roomName: "COATING 3",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 32,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-063",
    sterileFilterTag: "B10L3-FSL20",
    roomName: "COATING 4",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 33,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-064",
    sterileFilterTag: "B10L3-FSL22",
    roomName: "COATING 5",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 34,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-065",
    sterileFilterTag: "B10L3-FSL26",
    roomName: "COATING SOLUTION PREPARATION 3  (SOLUTION PREPARATION TANK)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 35,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-066",
    sterileFilterTag: "B10L3-FSL27",
    roomName: "COATING SOLUTION PREPARATION 4  (SOLUTION PREPARATION TANK)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 36,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-067",
    sterileFilterTag: "B10L3-FSL28",
    roomName: "COATING 6",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 37,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-072",
    sterileFilterTag: "B10L3-FSL10",
    roomName: "DRY GRANULATION 1 (ROLL COMPACTOR)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 38,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-073",
    sterileFilterTag: "B10L3-FSL09",
    roomName: "DRY GRANULATION 2 (LOW RH) (ROLL COMPACTOR)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 39,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-074",
    sterileFilterTag: "B10L3-FSL11",
    roomName: "DRY GRANULATION 3 (LOW RH) (ROLL COMPACTOR)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 40,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-079",
    sterileFilterTag: "B10L3-FSL05",
    roomName: "DRYING",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 41,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-085",
    sterileFilterTag: "B10L3-FSL06",
    roomName: "DRYING",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 43,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-104",
    sterileFilterTag: "B10L3-FSL30",
    roomName: "BINDER PREPARATION  (BINDER PREPARATION MACHINE)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 44,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-107",
    sterileFilterTag: "B10L3-FSL12",
    roomName: "WET GRANULATION 2 (LOW RH)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 45,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-120",
    sterileFilterTag: "B10L3-FSL31",
    roomName: "COMPRESSION 1  (TABLET COMPRESSION MACHINE)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 46,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-121",
    sterileFilterTag: "B10L3-FSL33",
    roomName: "COMPRESSION 2  (TABLET COMPRESSION MACHINE)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 47,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-122",
    sterileFilterTag: "B10L3-FSL36",
    roomName: "COMPRESSION 3 (LOW RH) (TABLET COMPRESSION MACHINE)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 48,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-123",
    sterileFilterTag: "B10L3-FSL13",
    roomName: "COMPRESSION 4 (TABLET COMPRESSION MACHINE)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 49,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-124",
    sterileFilterTag: "B10L3-FSL41",
    roomName: "COMPRESSION 5  (TABLET INSPECTION MACHINE)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 50,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-125",
    sterileFilterTag: "B10L3-FSL35",
    roomName: "COMPRESSION 6  (TABLET COMPRESSION MACHINE)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 51,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-126",
    sterileFilterTag: "B10L3-FSL34",
    roomName: "COMPRESSION 7  (TABLET COMPRESSION MACHINE)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 52,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-127",
    sterileFilterTag: "B10L3-FSL32",
    roomName: "COMPRESSION 8  (TABLET COMPRESSION MACHINE)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 53,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-136",
    sterileFilterTag: "B10L3-FSL19",
    roomName: "TABLET INSPECTION-P (LOW RH) (TABLET INSPECTION MACHINE) (DRUM TIPPER)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 54,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-143",
    sterileFilterTag: "B10L3-FSL18",
    roomName: "COATING SOLUTION PREPARATION-P (SOLUTION PREPARATION TANK)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 55,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-144",
    sterileFilterTag: "B10L3-FSL17",
    roomName: "COATING-P",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 56,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-145",
    sterileFilterTag: "B10L3-FSL16",
    roomName: "COMPRESSION 1-P (LOW RH) (TABLET COMPRESSION MACHINE)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 57,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-147",
    sterileFilterTag: "B10L3-FSL15",
    roomName: "COMPRESSION 2-P (TABLET COMPRESSION MACHINE)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 58,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-159",
    sterileFilterTag: "B10L3-FSL08",
    roomName: "BINDER PREPARATION-P  (BINDER PREPARATION MACHINE)",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 59,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-160",
    sterileFilterTag: "B10L3-FSL14",
    roomName: "DRY GRANULATION-P (LOW RH) (ROLL COMPACTOR)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 60,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-170",
    sterileFilterTag: "B10L3-FSL01",
    roomName: "DRYING-P",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 61,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-171",
    sterileFilterTag: "B10L3-FSL02",
    roomName: "TOOLS WASHING-P",
    using: true,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  },
  {
    id: 62,
    building: "B.10",
    floor: "FL.3",
    roomNo: "10-3-175",
    sterileFilterTag: "B10L3-FSL04",
    roomName: "DISPENSING 2-P (DISPENSING ISOLATOR)",
    using: false,
    sampling: false,
    samplingDate: "none",
    validationPlan: "Aug 2025",
    favorite: false
  }
];
